import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from '@/hooks/use-toast';

export interface OrderItem {
  productId: string;
  name: string;
  price: number;
  quantity: number;
  image?: string;
}

export interface Order {
  id: string;
  order_number: string;
  user_id: string;
  customer_name: string;
  customer_email: string;
  customer_phone: string | null;
  delivery_address: string;
  items: OrderItem[];
  subtotal: number;
  shipping: number;
  tax: number;
  total: number;
  payment_method: string;
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'out_for_delivery' | 'delivered' | 'cancelled';
  notes: string | null;
  created_at: string;
  updated_at: string;
}

interface CreateOrderData {
  customerName: string;
  customerEmail: string;
  customerPhone?: string;
  deliveryAddress: string;
  items: OrderItem[];
  subtotal: number;
  shipping: number;
  tax?: number;
  total: number;
  paymentMethod: string;
  notes?: string;
}

export function useOrders() {
  const { user } = useAuth();
  const [loading, setLoading] = useState(false);

  const createOrder = async (orderData: CreateOrderData): Promise<Order | null> => {
    if (!user) {
      toast({
        title: "Authentication required",
        description: "Please sign in to place an order.",
        variant: "destructive",
      });
      return null;
    }

    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('orders')
        .insert({
          user_id: user.id,
          order_number: '', // Will be generated by trigger
          customer_name: orderData.customerName,
          customer_email: orderData.customerEmail,
          customer_phone: orderData.customerPhone || null,
          delivery_address: orderData.deliveryAddress,
          items: JSON.stringify(orderData.items) as unknown as Record<string, unknown>,
          subtotal: orderData.subtotal,
          shipping: orderData.shipping,
          tax: orderData.tax || 0,
          total: orderData.total,
          payment_method: orderData.paymentMethod,
          notes: orderData.notes || null,
        } as any)
        .select()
        .single();

      if (error) throw error;

      const order = {
        ...data,
        items: typeof data.items === 'string' ? JSON.parse(data.items) : data.items,
      } as Order;

      // Send confirmation email
      await sendOrderStatusEmail({
        orderId: data.id,
        newStatus: 'pending',
        customerEmail: orderData.customerEmail,
        customerName: orderData.customerName,
        orderNumber: data.order_number,
      });

      toast({
        title: "Order placed successfully!",
        description: `Order #${data.order_number} has been created.`,
      });

      return order;
    } catch (error: any) {
      console.error('Error creating order:', error);
      toast({
        title: "Failed to create order",
        description: error.message,
        variant: "destructive",
      });
      return null;
    } finally {
      setLoading(false);
    }
  };

  const parseOrderData = (data: any): Order => ({
    ...data,
    items: typeof data.items === 'string' ? JSON.parse(data.items) : (data.items || []),
  });

  const fetchUserOrders = async (): Promise<Order[]> => {
    if (!user) return [];

    try {
      const { data, error } = await supabase
        .from('orders')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return (data || []).map(parseOrderData);
    } catch (error: any) {
      console.error('Error fetching orders:', error);
      return [];
    }
  };

  const fetchAllOrders = async (): Promise<Order[]> => {
    try {
      const { data, error } = await supabase
        .from('orders')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;
      return (data || []).map(parseOrderData);
    } catch (error: any) {
      console.error('Error fetching all orders:', error);
      return [];
    }
  };

  const updateOrderStatus = async (
    orderId: string,
    newStatus: Order['status'],
    sendEmail: boolean = true
  ): Promise<boolean> => {
    setLoading(true);
    try {
      // First get the order details for email
      const { data: orderData, error: fetchError } = await supabase
        .from('orders')
        .select('*')
        .eq('id', orderId)
        .single();

      if (fetchError) throw fetchError;

      const oldStatus = orderData.status;

      // Update the order status
      const { error: updateError } = await supabase
        .from('orders')
        .update({ status: newStatus })
        .eq('id', orderId);

      if (updateError) throw updateError;

      // Log status change in history
      await supabase.from('order_status_history').insert({
        order_id: orderId,
        old_status: oldStatus,
        new_status: newStatus,
        changed_by: user?.id || null,
      });

      // Send email notification
      if (sendEmail) {
        await sendOrderStatusEmail({
          orderId,
          newStatus,
          customerEmail: orderData.customer_email,
          customerName: orderData.customer_name,
          orderNumber: orderData.order_number,
        });
      }

      toast({
        title: "Order updated",
        description: `Order #${orderData.order_number} status changed to ${newStatus}`,
      });

      return true;
    } catch (error: any) {
      console.error('Error updating order status:', error);
      toast({
        title: "Failed to update order",
        description: error.message,
        variant: "destructive",
      });
      return false;
    } finally {
      setLoading(false);
    }
  };

  const sendOrderStatusEmail = async (params: {
    orderId: string;
    newStatus: string;
    customerEmail: string;
    customerName: string;
    orderNumber: string;
  }): Promise<void> => {
    try {
      const { error } = await supabase.functions.invoke('send-order-status-email', {
        body: params,
      });

      if (error) {
        console.error('Error sending email:', error);
      } else {
        console.log('Order status email sent successfully');
      }
    } catch (error) {
      console.error('Failed to send order status email:', error);
    }
  };

  const getOrderById = async (orderId: string): Promise<Order | null> => {
    try {
      const { data, error } = await supabase
        .from('orders')
        .select('*')
        .eq('id', orderId)
        .maybeSingle();

      if (error) throw error;
      return data ? parseOrderData(data) : null;
    } catch (error: any) {
      console.error('Error fetching order:', error);
      return null;
    }
  };

  const getOrderByNumber = async (orderNumber: string): Promise<Order | null> => {
    try {
      const { data, error } = await supabase
        .from('orders')
        .select('*')
        .eq('order_number', orderNumber)
        .maybeSingle();

      if (error) throw error;
      return data ? parseOrderData(data) : null;
    } catch (error: any) {
      console.error('Error fetching order by number:', error);
      return null;
    }
  };

  const getEsewaTransactionStatus = async (orderId: string): Promise<{
    status: string;
    ref_id: string | null;
    verified_at: string | null;
  } | null> => {
    try {
      const { data, error } = await supabase
        .from('esewa_transactions')
        .select('status, ref_id, verified_at')
        .eq('order_id', orderId)
        .maybeSingle();

      if (error) throw error;
      return data;
    } catch (error: any) {
      console.error('Error fetching eSewa transaction:', error);
      return null;
    }
  };

  return {
    loading,
    createOrder,
    fetchUserOrders,
    fetchAllOrders,
    updateOrderStatus,
    getOrderById,
    getOrderByNumber,
    getEsewaTransactionStatus,
  };
}
